# Generated by Django 6.0.3 on 2026-03-05 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('location_label', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('source', models.CharField(choices=[('google', 'Google'), ('yelp', 'Yelp'), ('homeadvisor', 'HomeAdvisor'), ('angi', 'Angi'), ('direct', 'Direct'), ('other', 'Other')], default='google', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('project_type', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-review_date'],
            },
        ),
    ]
