# Generated by Django 6.0.3 on 2026-03-05 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('service_areas', '0002_seed_initial_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='service_areas.servicearea'),
        ),
    ]
